name: ci

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

# env:
#     BRANCH_NAME = "123"
#   ECR_REPOSITORY: flask-app
#   EKS_CLUSTER_NAME: Kubernetes-demo 
#   AWS_REGION: us-east-1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -          
        name: Set up QEMU  # Add support for more platforms with QEMU (optional) 
        uses: docker/setup-qemu-action@v3   
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3         
      -
        name: Login to ECR
        uses: docker/login-action@v3
        with:
          registry: "753743851231.dkr.ecr.us-east-2.amazonaws.com/123456789"
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}         
        env:
            AWS_REGION: "us-east-2"
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: "753743851231.dkr.ecr.us-east-2.amazonaws.com/123456789:${{ github.run_number }}"


     
    
