name: ci

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v4
    -
      # Add support for more platforms with QEMU (optional)      
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3   
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3         
    -
      name: Login to ECR
      uses: docker/login-action@v3
      with:
        registry: public.ecr.aws/l5l6b5y3/gitactions
        username: ${{ secrets.AWS_ACCESS_KEY_ID }}
        password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}       
    # -
    #   name: Build and push
    #   uses: docker/build-push-action@v5
    #   with:
    #     context: .
    #     file: ./Dockerfile
    #     push: true
    #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/clockbox:latest


     
    
